### ISSUE TITLE
Not Working anymore

### ISSUE THREAD

**Issue by sammathur4** [Nithin005/lecturenotes.in-downloader#5]
Your program has stopped working for a while now.
Please have a look

**Comment by Nithin005** [comment]
the website seems to have changes quite a bit. the js files are obfuscated. I can no longer make this tool work.But
I am making a new chrome extension for downloading from lecturenotes.in with new features.
i will update here as soon as it is ready.

**Comment by Nithin005** [comment]
Try this @sammathur4: 
https://github.com/Nithin005/lecturenotes.in-dl.tampermonkey
