### ISSUE TITLE
fooling around you douche

### ISSUE THREAD

**Issue by piyush4for** [Nithin005/lecturenotes.in-downloader#6]
behen ke lund chutiyaan bana rha h hume . 3 baap ki aulaad

tranlate in english

**Comment by Nithin005** [comment]
Hey I want to say fuck you, if u dont like this dont open issue noob.

**Comment by piyush4for** [comment]
This tool was not working  . I am a linux user and want to find which is executible file to run this tool

**Comment by Nithin005** [comment]
# This Tool NO LONGER WORKS. Check 

### this [TamperMonkey Script](https://github.com/Nithin005/lecturenotes.in-dl.tampermonkey)(Works on Most Browsers) 

### OR 

### this [Firefox Extension](https://github.com/Nithin005/lecturenotes.in-chrome-extension)
